"""empty message

Revision ID: 4d530f83636b
Revises: 56d3cff236a7
Create Date: 2024-07-08 16:39:36.092300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d530f83636b'
down_revision = '56d3cff236a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('characters_favourite_id_fkey', type_='foreignkey')
        batch_op.drop_column('favourite_id')

    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'characters', ['character_id'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['planet_id'], ['id'])
        batch_op.create_foreign_key(None, 'vehicles', ['vehicle_id'], ['id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_favourite_id_fkey', type_='foreignkey')
        batch_op.drop_column('favourite_id')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint('vehicles_favourite_id_fkey', type_='foreignkey')
        batch_op.drop_column('favourite_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('vehicles_favourite_id_fkey', 'favourites', ['favourite_id'], ['id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('planets_favourite_id_fkey', 'favourites', ['favourite_id'], ['id'])

    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicle_id')
        batch_op.drop_column('planet_id')
        batch_op.drop_column('character_id')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('characters_favourite_id_fkey', 'favourites', ['favourite_id'], ['id'])

    # ### end Alembic commands ###
